call plug#begin()
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'raimondi/delimitMate'
Plug 'altercation/vim-colors-solarized'

" On-demand loading
Plug 'scrooloose/nerdtree'
call plug#end()

" Customize tabs
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
" Customize gitgutter
set updatetime=250
let g:gitgutter_sign_column_always = 1

" Map semicolon to colon
nmap ; :
noremap ;; ;

set number
